import { chromium } from "@playwright/test";
const OUT = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
const errs = []; p.on("pageerror", (e) => errs.push(String(e)));
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
await p.goto("http://localhost:4173/", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.screenshot({ path: `${OUT}/c-hero.png`, clip:{x:0,y:0,width:1440,height:860} });
await p.evaluate(() => document.querySelector("#see").scrollIntoView());
await p.waitForTimeout(4500);
await p.screenshot({ path: `${OUT}/c-see.png` });
console.log(errs.length ? "ERRORS: " + errs.join(" | ") : "ok");
await b.close();
